### ISSUE TITLE
 div element interfering with section 02. Work of portfolio

### ISSUE THREAD

**Issue by derkiab** [avneesh0612/portfolio#31]
When scrolling down your portfolio i found that a div element is interfering and blocking the user from clikcing the Visit links when they are in the center of the screen as shown here: 
![image](https://github.com/avneesh0612/portfolio/assets/110829988/299e40e7-4462-4a8c-bf15-0952bd064c4d)

**Comment by llcain** [comment]
Is this issue still open or is it closed?

**Comment by derkiab** [comment]
This is now closed.
